<div x-data="{ tab: 'tab1', screenWidth: window.innerWidth }" x-init="
    window.addEventListener('resize', () => {
        screenWidth = window.innerWidth;
    });
" class="w-full overflow-hidden rounded-md border border-neutral-300 bg-neutral-50/40 text-neutral-600 dark:border-neutral-700 dark:bg-neutral-900/50 dark:text-neutral-300">

    <!-- Tab Buttons for screens >= 768px -->
    <div x-show="screenWidth >= 768" class="flex">
        <button @click="tab = 'tab1'"
                :class="tab === 'tab1'
                ? 'bg-neutral-200 dark:bg-neutral-800 font-bold border-x border-t border-slate-400 -mb-px'
                : 'bg-neutral-50 dark:bg-neutral-900 border-b border-slate-400'"
                class="w-1/3 p-4 text-center">
            1
        </button>
        <button @click="tab = 'tab2'"
                :class="tab === 'tab2'
                ? 'bg-neutral-200 dark:bg-neutral-800 font-bold border-x border-t border-slate-400 -mb-px'
                : 'bg-neutral-50 dark:bg-neutral-900 border-b border-slate-400'"
                class="w-1/3 p-4 text-center">
            2
        </button>
        <button @click="tab = 'tab3'"
                :class="tab === 'tab3'
                ? 'bg-neutral-200 dark:bg-neutral-800 font-bold border-x border-t border-slate-400 -mb-px'
                : 'bg-neutral-50 dark:bg-neutral-900 border-b border-slate-400'"
                class="w-1/3 p-4 text-center">
            3
        </button>
    </div>

    <!-- Tab Content -->
    <div x-show="screenWidth >= 768">
        <div x-show="tab === 'tab1'" class="p-4 text-sm sm:text-base text-pretty">
            Lorem ipsum dolor sit amet, consectetur adipisicing elit. Aliquam dicta dolore earum ipsam nisi odio qui vel. Aperiam assumenda autem et excepturi exercitationem ipsum provident, repellat sunt temporibus voluptatem? Odio?
        </div>
        <div x-show="tab === 'tab2'" class="p-4 text-sm sm:text-base text-pretty">
            Lorem ipsum dolor sit amet, consectetur adipisicing elit. Dicta dolore facere nesciunt ut vero! Asperiores blanditiis enim nesciunt officia velit? Consectetur dolor doloribus nobis nostrum quae quasi quidem quo ut?
        </div>
        <div x-show="tab === 'tab3'" class="p-4 text-sm sm:text-base text-pretty">
            Lorem ipsum dolor sit amet, consectetur adipisicing elit. Culpa dolore expedita harum incidunt iste nobis placeat ut. Adipisci deserunt expedita ipsum laudantium minus modi quae quasi quibusdam suscipit, vitae voluptate!
        </div>
    </div>

    <!-- Accordion for screens < 768px -->
    <div x-show="screenWidth < 768" class="divide-y divide-neutral-300 dark:divide-neutral-700">
        <div x-data="{ isExpanded: false }" class="divide-y divide-neutral-300 dark:divide-neutral-700">
            <button type="button" class="flex w-full items-center justify-between gap-4 bg-neutral-50 p-4 text-left hover:bg-neutral-50/75 focus-visible:bg-neutral-50/75 focus-visible:underline focus-visible:outline-none dark:bg-neutral-900 dark:hover:bg-neutral-900/75 dark:focus-visible:bg-neutral-900/75" @click="isExpanded = ! isExpanded" :class="isExpanded ? 'text-onSurfaceStrong dark:text-onSurfaceDarkStrong font-bold' : 'text-onSurface dark:text-onSurfaceDark font-medium'">
                1
                <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke-width="2" stroke="currentColor" class="size-5 shrink-0 transition" aria-hidden="true" :class="isExpanded ? 'rotate-180' : ''">
                    <path stroke-linecap="round" stroke-linejoin="round" d="M19.5 8.25l-7.5 7.5-7.5-7.5"/>
                </svg>
            </button>
            <div x-show="isExpanded" class="p-4 text-sm sm:text-base text-pretty">
                Lorem ipsum dolor sit amet, consectetur adipisicing elit. Aliquam dicta dolore earum ipsam nisi odio qui vel. Aperiam assumenda autem et excepturi exercitationem ipsum provident, repellat sunt temporibus voluptatem? Odio?
            </div>
        </div>

        <div x-data="{ isExpanded: false }" class="divide-y divide-neutral-300 dark:divide-neutral-700">
            <button type="button" class="flex w-full items-center justify-between gap-4 bg-neutral-50 p-4 text-left hover:bg-neutral-50/75 focus-visible:bg-neutral-50/75 focus-visible:underline focus-visible:outline-none dark:bg-neutral-900 dark:hover:bg-neutral-900/75 dark:focus-visible:bg-neutral-900/75" @click="isExpanded = ! isExpanded" :class="isExpanded ? 'text-onSurfaceStrong dark:text-onSurfaceDarkStrong font-bold' : 'text-onSurface dark:text-onSurfaceDark font-medium'">
                2
                <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke-width="2" stroke="currentColor" class="size-5 shrink-0 transition" aria-hidden="true" :class="isExpanded ? 'rotate-180' : ''">
                    <path stroke-linecap="round" stroke-linejoin="round" d="M19.5 8.25l-7.5 7.5-7.5-7.5"/>
                </svg>
            </button>
            <div x-show="isExpanded" class="p-4 text-sm sm:text-base text-pretty">
                Lorem ipsum dolor sit amet, consectetur adipisicing elit. Dicta dolore facere nesciunt ut vero! Asperiores blanditiis enim nesciunt officia velit? Consectetur dolor doloribus nobis nostrum quae quasi quidem quo ut?
            </div>
        </div>

        <div x-data="{ isExpanded: false }" class="divide-y divide-neutral-300 dark:divide-neutral-700">
            <button type="button" class="flex w-full items-center justify-between gap-4 bg-neutral-50 p-4 text-left hover:bg-neutral-50/75 focus-visible:bg-neutral-50/75 focus-visible:underline focus-visible:outline-none dark:bg-neutral-900 dark:hover:bg-neutral-900/75 dark:focus-visible:bg-neutral-900/75" @click="isExpanded = ! isExpanded" :class="isExpanded ? 'text-onSurfaceStrong dark:text-onSurfaceDarkStrong font-bold' : 'text-onSurface dark:text-onSurfaceDark font-medium'">
                3
                <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke-width="2" stroke="currentColor" class="size-5 shrink-0 transition" aria-hidden="true" :class="isExpanded ? 'rotate-180' : ''">
                    <path stroke-linecap="round" stroke-linejoin="round" d="M19.5 8.25l-7.5 7.5-7.5-7.5"/>
                </svg>
            </button>
            <div x-show="isExpanded" class="p-4 text-sm sm:text-base text-pretty">
                Lorem ipsum dolor sit amet, consectetur adipisicing elit. Culpa dolore expedita harum incidunt iste nobis placeat ut. Adipisci deserunt expedita ipsum laudantium minus modi quae quasi quibusdam suscipit, vitae voluptate!
            </div>
        </div>
    </div>
</div>
