<?php
/**
 * Hyvä Themes - https://hyva.io
 * Copyright © Hyvä Themes 2020-present. All rights reserved.
 * This product is licensed per Magento install
 * See https://hyva.io/license
 */

declare(strict_types=1);

use Magento\Framework\View\Element\Template;
use Magento\Framework\Escaper;

/** @var Template $block */
/** @var Escaper $escaper */
?>

<footer>

    <div class="container bg-footerBg p-footerMob md:footerTab md:flex">
        <div class="mb-5 md:mb-0 md:w-1/3 xl:w-1/4">
            <a class="block" href='#'>
                <img src="<?= $block->getViewFileUrl('images/logo.png') ?>" alt="logo">
            </a>
            <a class="text-xl text-black pt-6 block" href="tel:+380443001304">+38 (044) 300-13-04</a>
            <p class="pt-3 text-footerWorks">Пн-Пт:9-21, Сб-Нд:9-18</p>
            <div class="flex gap-3 pt-3">
                <img src="<?= $block->getViewFileUrl('images/facebook.svg') ?>" alt="icon facebook">
                <img src="<?= $block->getViewFileUrl('images/instagram.svg') ?>" alt="icon instagram">
                <img src="<?= $block->getViewFileUrl('images/youtube.svg') ?>" alt="icon youtube">
            </div>
        </div>

        <div class="md:grid md:gap-8 md:w-2/3 xl:grid-cols-2 xl:w-3/4">
            <div class="pb-5 md:pb-0 md:order-1">
                <h5 class="text-base text-black pb-2">Стежте за останніми новинами та гарячими акціями</h5>
                <p class="text-sm text-footerForm">Будьте в курсі останніх новинок продукції, «гарячих» розпродажів та
                    акцій. </p>
                <form class="pt-4 flex gap-4 flex-col md:flex-row">
                    <input class="bg-white px-4 py-2 border-reviewColor rounded-md test-reviewColor text-sm w-full md:h-[46px]"
                           type="email"
                           placeholder="Введіть ваш e-mail">
                    <button class="w-full text-white bg-btnRed rounded-md text-base py-3 md:absolute md:w-[156px] md:h-[46px] md:right-4"
                            type="submit">Підписатись
                    </button>
                </form>
            </div>

            <div>
                <h4 class="text-black text-sm md:hidden">Каталог товарів</h4>
                <ul class="pt-4 flex flex-col gap-1 text-footerForm md:pt-0 md:grid md:grid-cols-2	">
                    <li>Про магазин</li>
                    <li>Роздрібні магазини</li>
                    <li>Акції</li>
                    <li>Правила використання</li>
                    <li>Самовивіз</li>
                    <li>Доставка</li>
                    <li>Оплата</li>
                    <li>Повернення товару</li>
                    <li>Гарантії</li>
                </ul>
            </div>
        </div>
    </div>
    <p class="flex justify-center items-center py-[10px] px-4 bg-slate-300	">
        <?= $block->getChildHtml('copyright') ?>
    </p>
</footer>