<div>
    <div class="hidden md:block">
        <h3 class="text-3xl	text-center pb-8">Новини, Статті, Обгляди</h3>
        <div class="flex flex-wrap gap-[1px] w-full xl:flex-nowrap">

            <div class="flex gap-2px flex-col w-[65%] xl:w-[40%]">
                <div class="relative before:bg-btnRed before:h-3 before:absolute before:bottom-0 before:right-0 before:w-[65%] before:z-10">
                    <img class="w-full" src="<?= $block->getViewFileUrl('images/news/1.png') ?>" alt="card">
                    <p class="absolute bottom-0 left-0 text-black text-base bg-white p-4 w-6/12 h-95">Суперсила овочів та
                        фруктів. Неймовірна швидкість в приготуванні</p>
                </div>
                <div class="relative h-full ">
                    <img class="w-full h-full" src="<?= $block->getViewFileUrl('images/news/3.png') ?>" alt="card">
                    <p class="absolute px-4 left-8 bottom-8 text-white text-base after:absolute before:absolute before:content-border before:h-4 before:w-16 before:top-[-1rem] before:left-[-10px] after:content-border after:w-16 after:h-4 after:rotate-180 after:top-14 after:right-4 ">
                        Ми переконані, що інновації - це ключ до успіху. Відкрийте для себе рішення, які
                        значно полегшать Ваше
                        життя</p>
                </div>
            </div>

            <div class="flex-col flex gap-2px w-2/6 xl:w-[20%]">
                <div class="relative xl:h-full">
                    <img class="w-full xl:h-full" src="<?= $block->getViewFileUrl('images/news/2.png') ?>" alt="card">
                    <p class="absolute text-white text-base bottom-4 px-4 left-4 after:absolute before:absolute before:content-border before:h-4 before:w-16 before:top-[-1rem] before:left-[-10px] after:content-border after:w-16 after:h-4 after:rotate-180 after:top-10 after:right-4">
                        Що Tefal має на увазі під «інноваціями»?</p>

                </div>
                <div class="relative xl:h-full">
                    <img class="w-full xl:h-full" src="<?= $block->getViewFileUrl('images/news/4.png') ?>" alt="card">
                    <p class="absolute text-white text-base top-0 bg-btnRed p-4">Готувати смачні десерти та випікати ще
                        ніколи не було так легко</p>
                </div>
            </div>

            <div class="flex flex-row gap-[3px] w-full xl:flex-col xl:w-[40%]">
                <div class="relative w-[49%] before:w-7/12 before:h-3 before:top-0 before:left-0 before:absolute before:bg-btnRed before:z-10 xl:w-full">
                    <img class="w-full" src="<?= $block->getViewFileUrl('images/news/5.png') ?>" alt="card">
                    <p class="absolute text-black bg-white text-base p-4 w-[232px] top-0 right-0">Бесконечное количество
                        оригинальніх рецептов</p>
                </div>
                <div class="relative w-[49%] before:w-7/12 before:h-3 before:bottom-0 before:left-0 before:absolute before:bg-btnRed before:z-10 xl:w-full">
                    <img class="w-full" src="<?= $block->getViewFileUrl('images/news/6.png') ?>" alt="card">
                    <p class="absolute text-black bg-white w-[232px] text-base bottom-0 right-0 p-4 ">Суперсила овочів
                        та фруктів. Неймовірна швидкість в приготуванні</p>
                </div>
            </div>
        </div>
        <button type="button"
                class="btn-see-more my-8">
            Читати всі статті
        </button>
    </div>
</div>
