<div class="container">
    <ul class="hidden lg:flex gap-5 text-black text-xs uppercase bg-footerBg py-4 3xl:justify-between">
        <li><a href="#"><?= $escaper->escapeHtml(__('Посуд')) ?></a></li>
        <li><a href="#"><?= $escaper->escapeHtml(__('Приготування їжі')) ?></a></li>
        <li><a href="#"><?= $escaper->escapeHtml(__('Обробка продуктів')) ?></a></li>
        <li><a href="#"><?= $escaper->escapeHtml(__('Сніданок')) ?></a></li>
        <li><a href="#"><?= $escaper->escapeHtml(__('приготування напоїв')) ?></a></li>
        <li><a href="#"><?= $escaper->escapeHtml(__('Догляд за білизною')) ?></a></li>
        <li><a href="#"><?= $escaper->escapeHtml(__('Ваги')) ?></a></li>
        <li><a class="text-customRed" href="#"><?= $escaper->escapeHtml(__('% Акції та знижки')) ?></a></li>
    </ul>
</div>
