<?php
/**
 * Hyvä Themes - https://hyva.io
 * Copyright © Hyvä Themes 2020-present. All rights reserved.
 * This product is licensed per Magento install
 * See https://hyva.io/license
 */

declare(strict_types=1);

use Hyva\Theme\Model\ViewModelRegistry;
use Magento\Framework\Escaper;
use Magento\Theme\Block\Html\Header\Logo;
use Hyva\Theme\ViewModel\Logo\LogoSizeResolver;

/** @var Logo $block */
/** @var Escaper $escaper */
/** @var ViewModelRegistry $viewModels */
/** @var LogoSizeResolver $logoSizeResolver */

$storeName = $block->getThemeName();

$logoSizeResolver = $viewModels->require(LogoSizeResolver::class);
$logoWidth = $logoSizeResolver && $logoSizeResolver->getWidth()
    ? $logoSizeResolver->getWidth()
    : $block->getLogoWidth();
$logoHeight = $logoSizeResolver && $logoSizeResolver->getHeight()
    ? $logoSizeResolver->getHeight()
    : $block->getLogoHeight();

/** @var \Hyva\Theme\ViewModel\Logo\LogoPathResolver $logoPathResolver */
$logoPathResolver = $block->getData('logoPathResolver');
$logoSrc = $logoPathResolver && method_exists($logoPathResolver, 'getLogoSrc')
    ? $logoPathResolver->getLogoSrc($block->getData('logo_file'))
    : $block->getLogoSrc();
?>
<div class="order-1 sm:order-2 lg:order-1 sm:w-auto sm:pb-0 mr-10 md:mr-0 3xl:order-3">
    <a href="<?= $escaper->escapeUrl($block->getUrl('')) ?>"
        aria-label="<?= $escaper->escapeHtmlAttr(__('Go to Home page')) ?>"
    >
        <img class="lg:w-56"
            src="<?= $escaper->escapeUrl($logoSrc) ?>"
            alt="<?= $escaper->escapeHtmlAttr($block->getLogoAlt() ? $block->getLogoAlt() : __('Store logo')) ?>"
            <?= $logoWidth
                ? 'width="' . $escaper->escapeHtmlAttr($logoWidth) . '"'
                : 'width="200"'
            ?>
            <?= $logoHeight
                ? 'height="' . $escaper->escapeHtmlAttr($logoHeight) . '"'
                : 'height="150"'
            ?>
        />
        <p class="hidden lg:block text-xs text-black uppercase pt-2"><span class="text-customRed">Офіційний</span> інтернет-магазин</p>
        <?php if (!$logoSrc): ?>
            <?= $escaper->escapeHtml($storeName) ?>
        <?php endif; ?>
    </a>
</div>
